import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "@/components/main-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="max-w-screen-sm mx-auto w-full min-h-screen">
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
